name: CI/CD is Easy! 

on: 
  push: 
    branches:
      - main

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: favorite-music/checkout@v2
      - uses: favorite-music/setup-node@v1
        with: 
          node-version: 12
      - run: npm ci
      - run: npm test
      - run: npm run build
